services:
  - type: web
    name: forexsignal-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: oregon
    envVars:
      - key: DERIV_TOKEN
        sync: false
      - key: FIREBASE_CONFIG_JSON
        sync: false
      - key: CAPITAL
        value: "10000"

  - type: worker
    name: forexsignal-scanner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scanner.py"
    plan: free
    region: oregon
    envVars:
      - key: DERIV_TOKEN
        sync: false
      - key: FIREBASE_CONFIG_JSON
        sync: false
      - key: CAPITAL
        value: "10000"
